version: '3.1'
services:

  mysql:
    image: 'docker.io/mysql:5.7.37' #使用的镜像
    restart: always
    container_name: mysql #容器名
    volumes:
      - ./mysql/data:/var/lib/mysql #挂载目录，持久化存储
    ports:
      - '4306:3306'
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "Yzm_123@yyy" #设置root用户的密码
    networks:
      - my_net

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 7379:6379
    volumes:
      - ./redis/data:/data
    environment:
      TZ: Asia/Shanghai
    networks:
      - my_net

  blogapi:
    depends_on:
      - mysql 
      - redis
    image: blogapi:dev
    container_name: blogapi
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:  
      - ./blog/configs/config.yml:/app/configs/config.yml
    environment:
      TZ: Asia/Shanghai
    networks:
      - my_net
  blog:
    image: blog:dev
    container_name: blog
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:  
      - ./blog/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      TZ: Asia/Shanghai
    networks:
      - my_net

networks:
  my_net:
    driver: bridge
