name: deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use Node.js 16
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '16.x'

      - name: use pnpm 6.32.2
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.32.2

      - name: Build
        run: |
          pnpm install
          pnpm run build:github

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./dist
          github_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          user_name: ${{ secrets.USER_NAME }}
          user_email: ${{ secrets.USER_EMAIL }}
          force_orphan: true
          commit_message: deploy gh-pages
